/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    ProfilesModal: typeof import('./src/components/ProfilesModal.vue')['default']
    ProgressBanner: typeof import('./src/components/ProgressBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupWizard: typeof import('./src/components/SetupWizard.vue')['default']
    UAlert: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USwitch: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_94171d66b808da36f9f03e72ba181813/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
